package com.cufe.deepweb.algorithm;

import com.cufe.deepweb.common.index.IndexClient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Map;
import java.util.Set;

/**
 * the implementation of all-in algorithm
 * this algorithm use all the terms generated by set-covering algorithm
 */
public class AllInAlgorithm extends SetCoverAlgorithm {
    private final Logger logger = LoggerFactory.getLogger(AllInAlgorithm.class);
    private IndexClient client;
    private AllInAlgorithm(Builder builder) {
        super(builder);
        this.client = builder.client;
    }

    @Override
    protected boolean isUpdate() {
        //only run one time at the beginning, update the index and confirm to update
        if (getSetCoverSize() == 0) {
            return true;
        }
        return false;
    }
    protected void update() {
        client.updateIndex();
    }

    @Override
    protected Map<String, Set<Integer>> getDocSetMap(String field, double low, double up) {
        return client.getDocSetMap(field, low, up);
    }

    @Override
    protected int getDocSize() {
        return client.getDocSize();
    }
    public static class Builder extends SetCoverAlgorithm.Builder {
        private IndexClient client;

        public Builder setIndexClient(IndexClient client) {
            this.client = client;
            return this;
        }

        public AllInAlgorithm build() {
            return new AllInAlgorithm(this);
        }
    }
}
